sudo: required
dist: trusty
language: node_js

node_js:
  - "7"

os:
  - linux
  - osx

addons:
  chrome: stable
  apt:
    packages:
      - jq
      - shellcheck
      - xvfb
      - dbus-x11

cache:
  directories:
    - node_modules

before_install:
  - npm config set progress=false

install:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew update; brew cleanup; brew cask cleanup; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew uninstall --force brew-cask; brew update; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew cask install --force google-chrome; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install shellcheck; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install jq; fi

  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then export DISPLAY=':99.0'; fi
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then sh -e /etc/init.d/xvfb start; fi

  - npm --progress false --loglevel warn install

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then google-chrome --version; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version; fi
  - shellcheck bin/*.sh
  - npm run lint
  - npm run dist
  # https://github.com/SeleniumHQ/docker-selenium/issues/87#issuecomment-187580115
  - if [ "$TRAVIS_OS_NAME" == 'linux' ];  then DBUS_SESSION_BUS_ADDRESS=/dev/null WECHATY_LOG=silly npm run test:chrome; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ];    then WECHATY_LOG=verbose  npm run nycava; fi
  - WECHATY_HEAD=chrome-headless npm run test:npm && echo 'Npm packing test is passed'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change

after_success:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then npm run coverage; fi

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
